#define MODEL_Root              0x24
#define MODEL_Axe               0x23
#define MODEL_AxeChain          0x22
#define MODEL_Lava              0x21
#define MODEL_LavaFlowBG        0x20
#define MODEL_LavaFlowR         0x1F
#define MODEL_LavaFlowL         0x1E
#define MODEL_BridgeBottom      0x1D
#define MODEL_BridgeTop         0x1C
#define MODEL_StageWallFront    0x1B
#define MODEL_SideWallR4        0x1A
#define MODEL_SideWallR3        0x19
#define MODEL_SideWallR2        0x18
#define MODEL_SideWallR1        0x17
#define MODEL_FrontWallR2       0x16
#define MODEL_FrontWallR1       0x15
#define MODEL_FloorRight        0x14
#define MODEL_SideWallL2        0x13
#define MODEL_SideWallL1        0x12
#define MODEL_FrontWallL2       0x11
#define MODEL_FrontWallL1       0x10
#define MODEL_FloorLeft         0xF
#define MODEL_BowserStatuePodium 0xE
#define MODEL_BowserStatueSupport 0xD
#define MODEL_StageWallFront    0xC
#define MODEL_BowserStatueBust  0xB
#define MODEL_StageWallSide     0xA
#define MODEL_StageWallFront    0x9
#define MODEL_CeilingBricks     0x8
#define MODEL_Rails             0x7
#define MODEL_BrickFloorBack    0x6
#define MODEL_BackWall          0x5
#define MODEL_Pillar5           0x4
#define MODEL_Pillar4           0x3
#define MODEL_Pillar3           0x2
#define MODEL_Pillar2           0x1
#define MODEL_Pillar1           0x0

